### ISSUE TITLE
User management fixes

### ISSUE THREAD

**Issue by inqbator** [openanswer/OpenAnswer#120]
If a user is deleted (I'm not sure we actually want to delete users, this happened while I was messing around in admin console):

- [x] User load_user will constantly keep throwing an AttributeError (deleted users aren't found in the db, resulting in a None when we query, and cause a NoneType has no attribute is_banned). This prevents the user from subsequently signing up again. I believe this is about to be fixed.
- [x] Messages api will crash for everyone when trying to load the messages of the deleted user - this should be made safe (this needs to be fixed!!).

This glitch occurred in beta once. Documenting it here because I'm not sure what happened:
- I changed user A's email, and at the same time, user B tried accessing the page and got automatically signed into user A's account. User B did not have an account. User B remained on User A's account until user B signed out and signed in again which prompted user B to create an account.

**Comment by openanswer** [comment]
Fixed in #121
