### ISSUE TITLE
ReactJS MVP

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#156]
This was originally caused by:

Why is OA broken on FF?

Users reported (and I can replicate) that sometimes the chat layout simply does not load in FF - there are no errors thrown in logs.

**Comment by openanswer** [comment]
I am taking on this opportunity to attempt to rewire the chat using reactjs. Maybe that way I don't have to chase a red herring.

**Comment by openanswer** [comment]
need to switch to react-bootstrap
https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic

**Comment by studyhog** [comment]
https://github.com/rexxars/react-markdown/issues/10

**Comment by studyhog** [comment]
We are now using react!
