### ISSUE TITLE
New section for DMs

### ISSUE THREAD

**Issue by EntersNewUserName79** [openanswer/OpenAnswer#17]
Don't know if its just me, but whenever I refresh the page, the dm disappears.

**Comment by openanswer** [comment]
It's not just you, those aren't really dms - more like whispers. We don't persist them in the database, so whenever you refresh they're gone. We probably need to add actual direct messaging.

**Comment by openanswer** [comment]
Actually we might get away with existing style DMs just by saving them to local storage. This would only persist on the machine and still disappear on cache clear.

**Comment by studyhog** [comment]
Duplicate of #13
