### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by hedgepiggy** [openanswer/OpenAnswer#28]
Right now, images are embedded into the chat regardless of size. It'd be nice to prevent images over a certain size from overflowing the chat box, perhaps something like https://www.npmjs.com/package/markdown-it-imsize would work well.

**Comment by openanswer** [comment]
Fixed in https://github.com/openanswer/OpenAnswer/commit/66191f65249c5b6fec2ce6fafcd2a4c72079ee12
