### ISSUE TITLE
Pause scroll in golden layout

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#37]
When a user scrolls up, stop scrolling them back down and notify of incoming messages instead.
- [x] Pause scrolling when a user scrolls up
- [x] Resume scrolling when a user scrolls down
- [x] Show a notification that informs the user of new messages if they had scrolled up
- [x] Don't show the notification if it's already present
- [x] Clicking on the notification should scroll the messages down and resume auto scroll.
- [x] Sending a new message should hide the notification, scroll down and resume auto scroll.
~~Later on:~~
~~- [ ] Increase the notification counter with new messages (similar to hangouts)~~

**Comment by studyhog** [comment]
This was done in #156
