### ISSUE TITLE
Request to add feature: Up arrow for last comment

### ISSUE THREAD

**Issue by night2222** [openanswer/OpenAnswer#39]
Request to use up arrow to autocomplete last comment, and if you keep pressing up it goes through last 10 or so comments.

**Comment by openanswer** [comment]
I had actually started looking at this and ran into some issues. Will resume as this is a really nice feature.

**Comment by studyhog** [comment]
This should be pretty easy now. In tab.js, add history to state, and on submit, append message to saved state.
On Up/Down arrow keys, fill in the textbox with the message accordingly.
