### ISSUE TITLE
Web stack migration

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#41]
Flask may not be best suited for what we're trying to accomplish with all the realtime data, chatting, whiteboarding, etc. Initially we ended up choosing flask because I was familiar with it, and it looked easy to learn. I'm not familiar with any web stacks so I can't speak of pros and cons of using Flask vs Node vs something else. We do frequently come along libraries that have great node/npm integration and it seems that web development would be less clunky if we were using the more common web stack (MEAN perhaps). Either way, development feels clunky.
My complaint with node is that from my limited experience of browsing Node tutorials, there seem to be a lot of different ways of doing things and everything is moving very quickly but maybe this is something we can't help in the web space in general.
I guess my hesitation for transferring over to node stems from the fact that we still haven't built a true 'prod' site and are very close. We've managed without it so far, switching over requires more months of setup, learning etc., and I don't see any immediate gains from the switch (I went over the server code for the whiteboard tutorial [here](http://code-and.coffee/post/2015/collaborative-drawing-canvas-node-websocket/), and it looks pretty straightforward to do in flask-socketio as well). Granted I don't see obvious advantages using flask either (apart from being more experienced with it). I would prefer to make the switch after we have a stable prod version of the site up and running.

**Comment by openanswer** [comment]
Throwing some ideas out there, not very organized yet as everything's a jumbled mess in my head right now:

1. Look into which framework is easier to get started with for front end. I think Node is probably the only js choice we have for backend (still hating the idea of a server running on js, but it can't all be that bad).
    - Angular vs React (I think react has better support for golden-layout?).
        - If we go with Angular, I think we should use Angular 2, but apparently golden-layout isn't fully supported (maybe we can make this work and even contribute to golden-layout - OS FTW!?).
        - React seems more lightweight and easier to get started with, but it might just be my gut feeling (I've tried a couple of Angular 2 tutorials, nothing in React so far though).
2. Mobile would be another thing to look into - I find myself using these sites on my phone more and more. Sure, we can build mobile friendly sites, but using mobile frameworks would let us use the native phone components (or sensors I presume). Both Angular and React have mobile frameworks, Angular based Ionic framework seems more mature.
    - Ionic
    - React Native.

**Comment by openanswer** [comment]
Some feedback from more experienced colleagues:

> I'd say flask is much narrower in its scope than node.
> flask helps you set up a web server with routing, auth, and templating.
> node is an entire JS development platform including language runtime, package/dependency manager and repo, and an async framework.
> Outside of something brand new with no dependencies, interoperability would be the reason to choose between node/js and flask/python.

**Comment by openanswer** [comment]
https://electron.atom.io/

**Comment by openanswer** [comment]
React has matured since, and is looking like a more feasible platform now. I am going to try and uplift some ui elements into react:
https://reactjs.org/docs/add-react-to-a-website.html

**Comment by studyhog** [comment]
#156 is the updated ticket.
