### ISSUE TITLE
NodeJS MVP

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#42]
- Database setup
- User authentication
    - http://passportjs.org/docs
- Socketio
- Deployment

**Comment by openanswer** [comment]
Looks like we want the MEAN.js stack (NOT MEAN.io):
http://meanjs.org/docs/0.5.x/

Use this to start the app:
https://www.djamware.com/post/58e0d15280aca75cdc948e4e/building-chat-application-using-mean-stack-angular-4-and-socketio

**Comment by studyhog** [comment]
#156 is the updated ticket.
