### ISSUE TITLE
is typing...

### ISSUE THREAD

**Issue by openanswer** [openanswer/OpenAnswer#9]
Add a typing indicator if there are users typing... This is pretty low priority.

**Comment by studyhog** [comment]
Current onKeyPress implementation doesn't work on mobile keypresses:

https://github.com/facebook/react/issues/6176
https://bugs.chromium.org/p/chromium/issues/detail?id=118639#c259
https://github.com/prakhar1989/react-tags/issues/199

Looks like an android chromium bug.

**Comment by studyhog** [comment]
Fixed in #229
